@echo off
echo Starting UniMarket...

echo Starting Backend (Port 8000)...
start /B py -3.11 -m uvicorn backend.main:app_with_sio --host 0.0.0.0 --port 8000

echo Starting Frontend (Port 5000)...
python server.py
